src_fmt:
  model/Frankfurt_epsilon/kappa5/{mag}/a{aspin}_i{inc:d}_R{Rhigh:d}/SgrA_{mag}_a{aspin}_i{incjk:d}_Rh{Rhigh:d}_Rl01_sigc01_snorm2.4_t{snapshot:d}_f230GHz.fits
dst_fmt:
  cache/Frankfurt_epsilon/kappa5/{mag}_a{aspin}_i{inc:d}/gt_Rh{Rhigh:d}_230GHz.h5
img_fmt:
  fits
order:
  - snapshot
