src_fmt:
  model/Hamr_varkappa/{freq}/{mag}_a{aspin:g}/Rhigh_{Rhigh:d}_Inclination_{inc:d}/{mag}_a{aspin2}_{snapshot:d}.h5
dst_fmt:
  cache/Hamr_varkappa/{mag}_a{aspin:g}_i{inc:d}/summ_Rh{Rhigh:d}_{freq}.tsv
img_fmt:
  ipole
params:
  - freq
  - mag
  - aspin
  - Rhigh
  - inc
# - aspin2
order:
  - snapshot
