src_fmt:
  model/Illinois_thermal/SEDs/{mag}a{aspin}_w{win:d}/sed_s{snapshot:d}_Rh{Rhigh:d}_i{inc:d}_r{realization:d}.h5
dst_fmt:
  cache/Illinois_thermal_w{win:d}/{mag}a{aspin}_i{inc:d}/sed_Rh{Rhigh:d}.h5
order:
  - snapshot
  - realization
