src_fmt:
  /xdisk/rtilanus/home/yitungtsang/SgrA_{aspin}_230.e9_{inc:d}/{snapshot:d}.h5
dst_fmt:
  cache/SPO2023/gt_SgrA/SgrA_a{aspin}_i{inc}_230.e9.h5
img_fmt:
  ipole
params:
#  - NGC
  - aspin
  - inc
order:
  - snapshot
